// Deze broncode is openbaar gemaakt vanwege een Woo-verzoek zodat deze 
// gericht is op transparantie en niet op hergebruik. Hergebruik van 
// de broncode is toegestaan onder de EUPL licentie, met uitzondering 
// van broncode waarvoor een andere licentie is aangegeven.
//
// Het archief waar dit bestand deel van uitmaakt is te vinden op:
//   https://github.com/MinBZK/woo-besluit-broncode-digid-app
//
// Eventuele kwetsbaarheden kunnen worden gemeld bij het NCSC via:
//   https://www.ncsc.nl/contact/kwetsbaarheid-melden
// onder vermelding van "Logius, openbaar gemaakte broncode DigiD-App" 
//
// Voor overige vragen over dit Woo-besluit kunt u mailen met open@logius.nl
//
// This code has been disclosed in response to a request under the Dutch
// Open Government Act ("Wet open Overheid"). This implies that publication 
// is primarily driven by the need for transparence, not re-use.
// Re-use is permitted under the EUPL-license, with the exception 
// of source files that contain a different license.
//
// The archive that this file originates from can be found at:
//   https://github.com/MinBZK/woo-besluit-broncode-digid-app
//
// Security vulnerabilities may be responsibly disclosed via the Dutch NCSC:
//   https://www.ncsc.nl/contact/kwetsbaarheid-melden
// using the reference "Logius, publicly disclosed source code DigiD-App" 
//
// Other questions regarding this Open Goverment Act decision may be
// directed via email to open@logius.nl
//
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiD.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobileAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigiD.Common.MobileAppResources", typeof(MobileAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak uw DigiD veiliger.
        /// </summary>
        public static string AP087_Header {
            get {
                return ResourceManager.GetString("AP087_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze optie niet meer tonen.
        /// </summary>
        public static string AP087_HideOption_Text {
            get {
                return ResourceManager.GetString("AP087_HideOption_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze opties niet meer tonen.
        /// </summary>
        public static string AP087_HideOptions_Text {
            get {
                return ResourceManager.GetString("AP087_HideOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altijd inloggen in 2 stappen.
        /// </summary>
        public static string AP087_Item_2fa_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2 stappen inloggen.
        /// </summary>
        public static string AP087_Item_2fa_Header {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met deze instelling zijn uw persoonlijke gegevens beter beschermd. U logt dan altijd in met de DigiD app, sms-controle of een identiteitsbewijs..
        /// </summary>
        public static string AP087_Item_2fa_Message {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres toevoegen.
        /// </summary>
        public static string AP087_Item_Email_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_Email_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string AP087_Item_Email_Header {
            get {
                return ResourceManager.GetString("AP087_Item_Email_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer uw e-mailadres zodat wij contact met u kunnen opnemen. Bijvoorbeeld als er iets wijzigt in uw DigiD..
        /// </summary>
        public static string AP087_Item_Email_Message {
            get {
                return ResourceManager.GetString("AP087_Item_Email_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-check uitvoeren.
        /// </summary>
        public static string AP087_Item_IDCheck_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-check.
        /// </summary>
        public static string AP087_Item_IDCheck_Header {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan uw rijbewijs, identiteitskaart of paspoort om uw DigiD betrouwbaarder te maken. Dit is nodig om in te loggen bij organisaties die uw privacygevoelige gegevens bewaren..
        /// </summary>
        public static string AP087_Item_IDCheck_Message {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten aanzetten.
        /// </summary>
        public static string AP087_Item_Messages_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App berichten.
        /// </summary>
        public static string AP087_Item_Messages_Header {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De app kan u berichten sturen. Bijvoorbeeld als er iets wijzigt in uw DigiD..
        /// </summary>
        public static string AP087_Item_Messages_Message {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met deze instellingen wordt het inloggen met de app nog veiliger..
        /// </summary>
        public static string AP087_Message_Multiple {
            get {
                return ResourceManager.GetString("AP087_Message_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met deze instelling wordt het inloggen met de app nog veiliger..
        /// </summary>
        public static string AP087_Message_Single {
            get {
                return ResourceManager.GetString("AP087_Message_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak uw DigiD app nog veiliger.
        /// </summary>
        public static string Landing_Preference_Header {
            get {
                return ResourceManager.GetString("Landing_Preference_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik hier voor meer informatie.
        /// </summary>
        public static string Landing_Preference_Message {
            get {
                return ResourceManager.GetString("Landing_Preference_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string M20_Dutch {
            get {
                return ResourceManager.GetString("M20_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string M20_English {
            get {
                return ResourceManager.GetString("M20_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string M20_Message {
            get {
                return ResourceManager.GetString("M20_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string M20_Title {
            get {
                return ResourceManager.GetString("M20_Title", resourceCulture);
            }
        }
    }
}
