// De openbaarmaking van dit bestand is in het kader van de WOO geschied en 
// dus gericht op transparantie en niet op hergebruik. In het geval dat dit 
// bestand hergebruikt wordt, is de EUPL licentie van toepassing, met 
// uitzondering van broncode waarvoor een andere licentie is aangegeven.
//
// Het archief waar dit bestand deel van uitmaakt is te vinden op:
//   https://github.com/MinBZK/woo-verzoek-broncode-digid-app
//
// Eventuele kwetsbaarheden kunnen worden gemeld bij het NCSC via:
//   https://www.ncsc.nl/contact/kwetsbaarheid-melden
// onder vermelding van "Logius, openbaar gemaakte broncode DigiD-App" 
//
// Voor overige vragen over dit WOO-verzoek kunt u mailen met:
//   mailto://open@logius.nl
//
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiD.Common {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobileAppResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileAppResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DigiD.Common.MobileAppResources.en", typeof(MobileAppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AP087_Header {
            get {
                return ResourceManager.GetString("AP087_Header", resourceCulture);
            }
        }
        
        public static string AP087_Message_Single {
            get {
                return ResourceManager.GetString("AP087_Message_Single", resourceCulture);
            }
        }
        
        public static string AP087_Item_IDCheck_Message {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_Message", resourceCulture);
            }
        }
        
        public static string AP087_Item_IDCheck_Header {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_Header", resourceCulture);
            }
        }
        
        public static string AP087_Item_IDCheck_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_IDCheck_ButtonText", resourceCulture);
            }
        }
        
        public static string AP087_Item_Email_Header {
            get {
                return ResourceManager.GetString("AP087_Item_Email_Header", resourceCulture);
            }
        }
        
        public static string AP087_Item_Email_Message {
            get {
                return ResourceManager.GetString("AP087_Item_Email_Message", resourceCulture);
            }
        }
        
        public static string AP087_Item_Messages_Header {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_Header", resourceCulture);
            }
        }
        
        public static string AP087_Item_Messages_Message {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_Message", resourceCulture);
            }
        }
        
        public static string AP087_Item_2fa_Header {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_Header", resourceCulture);
            }
        }
        
        public static string AP087_Item_2fa_Message {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_Message", resourceCulture);
            }
        }
        
        public static string AP087_HideOptions_Text {
            get {
                return ResourceManager.GetString("AP087_HideOptions_Text", resourceCulture);
            }
        }
        
        public static string AP087_HideOption_Text {
            get {
                return ResourceManager.GetString("AP087_HideOption_Text", resourceCulture);
            }
        }
        
        public static string AP087_Item_Email_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_Email_ButtonText", resourceCulture);
            }
        }
        
        public static string AP087_Item_Messages_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_Messages_ButtonText", resourceCulture);
            }
        }
        
        public static string AP087_Item_2fa_ButtonText {
            get {
                return ResourceManager.GetString("AP087_Item_2fa_ButtonText", resourceCulture);
            }
        }
        
        public static string Landing_Preference_Header {
            get {
                return ResourceManager.GetString("Landing_Preference_Header", resourceCulture);
            }
        }
        
        public static string Landing_Preference_Message {
            get {
                return ResourceManager.GetString("Landing_Preference_Message", resourceCulture);
            }
        }
        
        public static string AP087_Message_Multiple {
            get {
                return ResourceManager.GetString("AP087_Message_Multiple", resourceCulture);
            }
        }
        
        public static string M20_Message {
            get {
                return ResourceManager.GetString("M20_Message", resourceCulture);
            }
        }
        
        public static string M20_Title {
            get {
                return ResourceManager.GetString("M20_Title", resourceCulture);
            }
        }
        
        public static string M20_English {
            get {
                return ResourceManager.GetString("M20_English", resourceCulture);
            }
        }
        
        public static string M20_Dutch {
            get {
                return ResourceManager.GetString("M20_Dutch", resourceCulture);
            }
        }
    }
}
